model:
  name: two_view_pipeline
  extractor:
    name: extractors.joint_point_line_extractor
    aliked_model_name: "aliked-n16"
    max_num_keypoints: 2048  # setting for training, for eval: -1
    detection_threshold: 0.0
    nms_radius: 3
    training:
      do: False
    checkpoint: /local/home/rkreft/shared_team_folder/outputs/training/focal_loss_experiments/rk_focal_threshDF_focal/checkpoint_best.tar
    #checkpoint: /local/home/rkreft/shared_team_folder/outputs/training/rk_pold2gt_oxparis_focal/checkpoint_best.tar 
    #checkpoint: /local/home/rkreft/shared_team_folder/outputs/training/rk_pold2gt_oxparis_base_hard_gt/checkpoint_best.tar  # if given load model weights from this checkpoint
    timeit: False  # override timeit: False from BaseModel
    line_detection: # default conf is the one from POLD 2 Line Detector
      do: True
      conf:
        num_sample: 8
        num_sample_strong: 150
        max_point_size: 1500
        distance_map:
          threshold: 0.5
          avg_filter_size: 13
          avg_filter_padding: 6
          avg_filter_stride: 1
          max_value: 5
          inlier_ratio: 0.8
          max_accepted_mean_value: 0.4
        mlp_conf:
          name: gluefactory.models.lines.pold2_mlp
          has_angle_field: True
          has_distance_field: True
          num_line_samples: 150
          mlp_hidden_dims: [256, 128, 128, 64, 32]
          pred_threshold: 0.9
          weights: /local/home/Point-Line/outputs/training/pold2_mlp_gen+train_run1/checkpoint_best.tar
  matcher:
    name: matchers.nn_point_line
benchmarks:
  megadepth1500:
    data:
    preprocessing:
      side: long
      resize: 1600
    eval:
      estimator: poselib
      ransac_th: -1
  megadepth1500_extended:
    data:
    preprocessing:
      side: long
      resize: 1600
    eval:
      estimator: poselib
      ransac_th: -1
    model:
      extractor:
        max_num_keypoints: 500 # overwrite config above
  hpatches:
    eval:
      estimator: poselib
      ransac_th: -1
    model:
      extractor:
        max_num_keypoints: 500 # overwrite config above
  hpatches_extended:
    eval:
      estimator: poselib
      ransac_th: -1
    model:
      extractor:
        max_num_keypoints: 500 # overwrite config above

