model:
    name: two_view_pipeline
    extractor:
        name: lines.deeplsd
        model_conf:
            detect_lines: True
            max_num_lines: 2000
            line_detection_params:
                merge: False

    matcher:
        name: matchers.line_matcher
        line_dist: orth
benchmarks:
    megadepth1500:
        data:
            preprocessing:
                side: long
                resize: 1600
        eval:
            estimator: opencv
            ransac_th: 0.5
    hpatches_lines:
        data:
            preprocessing:
                side: long
                resize: 800
        use_points: False
        use_lines: True
    rdnim_lines:
        data:
            preprocessing:
                resize: 800
                side: long
        use_points: False
        use_lines: True
