model:
    name: two_view_pipeline
    extractor:
        name: extractors.xfeat  # XFeat - Sparse model, use xfeat_dense for dense model
        max_num_keypoints: 4096
        detection_threshold: 0.05
        pretrained: True
        model_name: xfeat
        get_sparse_outputs: True
        force_num_keypoints: True
        preprocess: True
        NMS:
            threshold: 0.05
            kernel_size: 5
    matcher:
        name: matchers.nearest_neighbor_matcher
benchmarks:
    megadepth1500:
        data:
            preprocessing:
                side: long
                resize: 1600
        eval:
            estimator: poselib
            ransac_th: -1
        model:
            extractor:
                max_num_keypoints: 2048
    hpatches:
        data:
            preprocessing:
                side: long
                resize: 800
        eval:
            estimator: poselib
            ransac_th: -1
        model:
            extractor:
                max_num_keypoints: 1024  # overwrite config above
