model:
    name: gluefactory.models.two_view_pipeline
    extractor:
        name: gluefactory.models.lines.wireframe
        point_extractor:
            name: extractors.superpoint_open
            max_num_keypoints: 512
            force_num_keypoints: True
            detection_threshold: -1
            nms_radius: 3
            trainable: False
        line_extractor:
            name: gluefactory.models.lines.lsd
            trainable: False
            max_num_lines: 512
            force_num_lines: False
            min_length: 15
        wireframe_params:
            merge_points: True
            merge_line_endpoints: True
            nms_radius: 3

benchmarks:
    hpatches:
        eval:
            estimator: homography_est
            ransac_th: -1    # [1., 1.5, 2., 2.5, 3.]
    megadepth1500:
        data:
            preprocessing:
                side: long
                resize: 1600
        eval:
            estimator: poselib
            ransac_th: -1
    eth3d:
        ground_truth:
            name: gluefactory.models.matchers.depth_matcher
            use_lines: True
        eval:
            plot_methods: [ ]    # ['sp+NN', 'sp+sg', 'superpoint+lsd+gluestick']
            plot_line_methods: [ ]    # ['superpoint+lsd+gluestick', 'sp+deeplsd+gs']
    wireframe:
        eval:
            "distance": "orthogonal"
            "distance_thresh": [1, 3, 5, 7, 100]
            "plot_images": False
        data:
            "size": -1 # -1 for full size
            "preprocessing":
                "resize": [640, 480]